export const dailyQuotes = [
	"I am Love",
	"I am Whole",
	"I am Loved",
	"I am Space",
	"I am Empty",
	"I am Compassion",
	"I am Stillness",
	"I am Flow",
	"I am Harmony",
	"I am Balance",
	"I am Presence",
	"I am Peace",
	"I am Breath",
	"I am Awareness",
	"I am Silence",
	"I am Nature",
	"I am Freedom",
	"I am Energy",
	"I am Light",
	"I am Acceptance",
	"I am Strength",
	"I am Softness",
	"I am Patience",
	"I am Clarity",
	"I am Unity",
	"I am Gratitude",
	"I am Infinite",
	"I am Tranquility",
	"I am Centered",
	"I am Connection",
	"I am Openness",
	"I am Simplicity",
	"I am Gentle Power",
	"I am Wuji",
	"Be Still",
	"Return to Center",
	"Breathe Deeply",
	"Embrace the Flow",
	"Stand Like a Mountain",
	"Move Like Water",
	"Rest in Emptiness",
	"Smile Within",
	"Listen to Silence",
	"Walk in Harmony",
	"The Way is Simple",
];
